spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: mysql://localhost:3306/mytest?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
mybatis:
  mapper-locations: mapper/**.xml
